name: Publish App

on: [release]

jobs:
  build:
    name: Publish App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install dependencies
      run: npm ci
    - name: Build App
      run: npm run build --if-present
      env:
        CI: true
    - name: Commit to gh-pages
      uses: stefanzweifel/git-auto-commit-action@v4.1.4
      with:
        commit_message: Publish distribution files.
        file_pattern: dist/\*.js
        branch: test-actions